server:
  port: 9090
---
spring:
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: nt-ms1
          uri: http://localhost:5052/
          predicates:
            - Path=/api2/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: nt-ms2
          uri: http://localhost:5051/
          predicates:
            - Path=/auth/**, /api/**
